vsim -novopt work.icf_processor

add wave -noupdate -divider ICF\ Processor\ Test


# inputs
add wave -noupdate -divider Inputs
add wave -position end  sim:/icf_processor/i_Clock_160MHz
add wave -position end  sim:/icf_processor/i_reset
add wave -position end  sim:/icf_processor/i_bus
add wave -position end  sim:/icf_processor/i_enable
add wave -position end  sim:/icf_processor/i_ram_counter
#add wave -position end  sim:/icf_processor/i_sppram_id_dv


# outputs
add wave -noupdate -divider Outputs
add wave -position end  sim:/icf_processor/o_bus
add wave -position end  sim:/icf_processor/o_enable
add wave -position end  sim:/icf_processor/o_ram_counter
#add wave -position end  sim:/icf_processor/o_sppram_id_dv


# signals
add wave -noupdate -divider Signals
add wave -position end  sim:/icf_processor/state

add wave -noupdate -divider Counter
add wave -position end  sim:/icf_processor/c_en
add wave -position end  sim:/icf_processor/co_value

add wave -noupdate -divider Sorter
add wave -position end  sim:/icf_processor/s_en
add wave -position end  sim:/icf_processor/s_odd
add wave -position end  sim:/icf_processor/si_bus
add wave -position end  sim:/icf_processor/so_bus

add wave -noupdate -divider flagger
add wave -position end  sim:/icf_processor/f_en
add wave -position end  sim:/icf_processor/fo_bus


# start clock
force -freeze sim:/icf_processor/i_Clock_160MHz 1 0, 0 {2000 ps} -r 4000ps

# reset
force -freeze sim:/icf_processor/i_reset 1 0
force -freeze sim:/icf_processor/i_reset 0 1

# enable for round one
force -freeze sim:/icf_processor/i_enable 0 0
force -freeze sim:/icf_processor/i_enable 1 2

#enable for round two
force -freeze sim:/icf_processor/i_enable 0 320
force -freeze sim:/icf_processor/i_enable 1 322

# ram counter - just say 64
force -freeze sim:/icf_processor/i_ram_counter 001000000 0

# load datatrains at correct clock cycles
# load from file generated by processor_i_bus c++ program
source ../gen_scripts/processor_unsorted.tcl
source ../gen_scripts/processor_unsorted1.tcl

# run for 160 clock cycles plus one for the reset at the start
run 644ns
