vsim -novopt work.sppif_top
config wave -signalnamewidth 1


##layout
add wave -noupdate -divider SPP\ Isolation\ Top
add wave -position end sim:/sppif_top/clk
add wave -position end sim:/sppif_top/rst

add wave -noupdate -divider From\ Router
add wave -position end sim:/sppif_top/rd_en
add wave -position end sim:/sppif_top/rd_addr
add wave -position end sim:/sppif_top/rd_data

add wave -noupdate -divider From\ Count\ Ram
add wave -position end sim:/sppif_top/ram_bcid
add wave -position end sim:/sppif_top/ram_size

add wave -noupdate -divider To\ MEP
add wave -position end sim:/sppif_top/wr_en
add wave -position end sim:/sppif_top/wr_addr
add wave -position end sim:/sppif_top/wr_data

##waves
#start clock and reset to initial conditions
force -freeze sim:/sppif_top/clk 1 0, 0 {3125 ps} -r 6.25ns
force -freeze sim:/sppif_top/rst 1 0
force -freeze sim:/sppif_top/rst 0 5ns

#ram size = 2
for {set i 0}  {$i < 8} {incr i} {
  force -freeze sim:/sppif_top/ram_size($i) 0 0
}
force -freeze sim:/sppif_top/ram_size(1) 1 1

#load random data into rd_data from file generated by bcid_gen
source simulation/rd_data_gen.tcl
